'use strict';

function freezeObjectTree(value) {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const child of Object.values(value)) freezeObjectTree(child);
  }
  return value;
}

const ROLES = freezeObjectTree({
  STAFF: 'STAFF',
  ADMIN: 'ADMIN',
});

const ORDER_STATUS = freezeObjectTree({
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  ORDERED: 'ORDERED',
  PARTIALLY_RECEIVED: 'PARTIALLY_RECEIVED',
  RECEIVED: 'RECEIVED',
  NOTIFIED: 'NOTIFIED',
  PATIENT_RECEIVED: 'PATIENT_RECEIVED',
  PATIENT_NO_SHOW: 'PATIENT_NO_SHOW',
  APPOINTMENT_RESCHEDULED: 'APPOINTMENT_RESCHEDULED',
  CANCEL_REQUESTED: 'CANCEL_REQUESTED',
  CANCEL_REJECTED: 'CANCEL_REJECTED',
  PARTIALLY_CANCELLED: 'PARTIALLY_CANCELLED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
});

const ITEM_STATUS = freezeObjectTree({
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  ORDERED: 'ORDERED',
  PARTIALLY_RECEIVED: 'PARTIALLY_RECEIVED',
  RECEIVED: 'RECEIVED',
  CANCEL_REQUESTED: 'CANCEL_REQUESTED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
});

const ERROR_CODES = freezeObjectTree({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  ACCESS_DENIED: 'ACCESS_DENIED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  ORDER_VERSION_CONFLICT: 'ORDER_VERSION_CONFLICT',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  REQUEST_REPLAY: 'REQUEST_REPLAY',
});

// These lists are intentionally the only fields a later write service may pass to
// the diff engine. Identity, ownership, status, audit and version values are not editable.
const EDITABLE_ORDER_FIELDS = Object.freeze([
  'DepartmentCode',
  'HN',
  'Notes',
  'PatientEmail',
  'PatientName',
  'PatientPhone',
  'RequiredDate',
]);

const EDITABLE_ORDER_ITEM_FIELDS = Object.freeze([
  'CategoryCode',
  'Instructions',
  'MedicationCode',
  'MedicationName',
  'Notes',
  'Quantity',
  'Unit',
]);

const MASTER_DATA_DEFAULTS = freezeObjectTree({
  departments: [],
  medicationCategories: [],
  medications: [],
});

const ORDER_TRANSITIONS = freezeObjectTree({
  [ORDER_STATUS.SUBMITTED]: [ORDER_STATUS.UNDER_REVIEW, ORDER_STATUS.ORDERED, ORDER_STATUS.CANCEL_REQUESTED, ORDER_STATUS.CANCELLED, ORDER_STATUS.REJECTED],
  [ORDER_STATUS.UNDER_REVIEW]: [ORDER_STATUS.ORDERED, ORDER_STATUS.PARTIALLY_RECEIVED, ORDER_STATUS.RECEIVED, ORDER_STATUS.CANCEL_REQUESTED, ORDER_STATUS.CANCELLED, ORDER_STATUS.REJECTED],
  [ORDER_STATUS.ORDERED]: [ORDER_STATUS.PARTIALLY_RECEIVED, ORDER_STATUS.RECEIVED, ORDER_STATUS.CANCEL_REQUESTED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PARTIALLY_RECEIVED]: [ORDER_STATUS.RECEIVED, ORDER_STATUS.PARTIALLY_CANCELLED, ORDER_STATUS.CANCEL_REQUESTED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.RECEIVED]: [ORDER_STATUS.NOTIFIED, ORDER_STATUS.CANCEL_REQUESTED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.NOTIFIED]: [ORDER_STATUS.PATIENT_RECEIVED, ORDER_STATUS.PATIENT_NO_SHOW, ORDER_STATUS.APPOINTMENT_RESCHEDULED, ORDER_STATUS.CANCEL_REQUESTED],
  [ORDER_STATUS.PATIENT_NO_SHOW]: [ORDER_STATUS.APPOINTMENT_RESCHEDULED, ORDER_STATUS.PATIENT_RECEIVED, ORDER_STATUS.CANCEL_REQUESTED],
  [ORDER_STATUS.APPOINTMENT_RESCHEDULED]: [ORDER_STATUS.NOTIFIED, ORDER_STATUS.PATIENT_RECEIVED, ORDER_STATUS.PATIENT_NO_SHOW, ORDER_STATUS.CANCEL_REQUESTED],
  [ORDER_STATUS.CANCEL_REQUESTED]: [ORDER_STATUS.CANCELLED, ORDER_STATUS.CANCEL_REJECTED],
  [ORDER_STATUS.CANCEL_REJECTED]: [ORDER_STATUS.UNDER_REVIEW, ORDER_STATUS.ORDERED, ORDER_STATUS.PARTIALLY_RECEIVED, ORDER_STATUS.RECEIVED, ORDER_STATUS.NOTIFIED],
  [ORDER_STATUS.PARTIALLY_CANCELLED]: [ORDER_STATUS.RECEIVED, ORDER_STATUS.NOTIFIED, ORDER_STATUS.COMPLETED],
  [ORDER_STATUS.PATIENT_RECEIVED]: [ORDER_STATUS.COMPLETED],
  [ORDER_STATUS.CANCELLED]: [],
  [ORDER_STATUS.COMPLETED]: [],
  [ORDER_STATUS.REJECTED]: [],
});

const ITEM_TRANSITIONS = freezeObjectTree({
  [ITEM_STATUS.SUBMITTED]: [ITEM_STATUS.UNDER_REVIEW, ITEM_STATUS.ORDERED, ITEM_STATUS.PARTIALLY_RECEIVED, ITEM_STATUS.RECEIVED, ITEM_STATUS.CANCEL_REQUESTED, ITEM_STATUS.CANCELLED],
  [ITEM_STATUS.UNDER_REVIEW]: [ITEM_STATUS.ORDERED, ITEM_STATUS.PARTIALLY_RECEIVED, ITEM_STATUS.RECEIVED, ITEM_STATUS.CANCEL_REQUESTED, ITEM_STATUS.CANCELLED],
  [ITEM_STATUS.ORDERED]: [ITEM_STATUS.PARTIALLY_RECEIVED, ITEM_STATUS.RECEIVED, ITEM_STATUS.CANCEL_REQUESTED, ITEM_STATUS.CANCELLED],
  [ITEM_STATUS.PARTIALLY_RECEIVED]: [ITEM_STATUS.RECEIVED, ITEM_STATUS.CANCEL_REQUESTED, ITEM_STATUS.CANCELLED],
  [ITEM_STATUS.RECEIVED]: [ITEM_STATUS.COMPLETED, ITEM_STATUS.CANCEL_REQUESTED, ITEM_STATUS.CANCELLED],
  [ITEM_STATUS.CANCEL_REQUESTED]: [ITEM_STATUS.CANCELLED, ITEM_STATUS.SUBMITTED, ITEM_STATUS.UNDER_REVIEW, ITEM_STATUS.ORDERED, ITEM_STATUS.PARTIALLY_RECEIVED, ITEM_STATUS.RECEIVED],
  [ITEM_STATUS.CANCELLED]: [],
  [ITEM_STATUS.COMPLETED]: [],
});

module.exports = Object.freeze({
  ROLES,
  ORDER_STATUS,
  ITEM_STATUS,
  ERROR_CODES,
  EDITABLE_ORDER_FIELDS,
  EDITABLE_ORDER_ITEM_FIELDS,
  MASTER_DATA_DEFAULTS,
  ORDER_TRANSITIONS,
  ITEM_TRANSITIONS,
});
